Control timeseries
e2nIEE/pandapipes pull request #402
Opened 2022-08-29 10:19 UTC by SimonRubenDrauz

- bugfix in run control multinet
- adding an in-between level 'nets' in ctrl_variables

2022-08-29 14:59 UTC, jkisse requested changes

2022-08-29 15:39 UTC, SimonRubenDrauz commented on pandapipes/multinet/control/run_control_multinet.py
> +        rel_levelorder = any(rel_levelorder)
rel_levelorder should be in my opinion always an array of booleans. Therefore, it should be okay. Any doubts or examples?

2022-08-30 08:24 UTC, jkisse commented on pandapipes/multinet/control/run_control_multinet.py
> +        rel_levelorder = any(rel_levelorder)
I see, you're right. I confused it with the level number. Seems fine then

2022-08-30 08:25 UTC, jkisse approved these changes

2022-08-30 08:59 UTC, merged